### PR TITLE
Updated readme.md to include instructions for preparing an Arch linux…

### PR DESCRIPTION
**Pull request by cdwijs**
… system

### CODE REVIEW

**Comment by cdwijs** [comment]
This pull request addresses this issue:
https://github.com/raspberrypi/picoprobe/issues/92

**Comment by aallan** [comment]
We don't explicitly support any Linux distribution except our own Raspberry Pi OS, which is a Debian-derived distribution. Our instructions are verified on Raspberry Pi OS, and will *probably* work on more or less out of the box on Debian or other Debian-derived system. However users of other distributions, like Arch, will need to check if there are any additional steps needed for their operating system. We can't add sections to support all of the alternative distribtion.

Additionally, the README file in the repository contains short-form instructions for installation, and more detailed instructions on Picoprobe and RP2040 development in general with the C SDK can be found in the [Getting started with Raspberry Pi Pico](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf) and [Raspberry Pi Pico C/C++ SDK](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf) books.

**Comment by cdwijs** [comment]
"We don't explicitly support any Linux distribution except our own Raspberry Pi OS". 

Fair point, supporting multiple distributions can take up a lot of time, and that may not be worth it.

"Additionally, the README file in the repository contains short-form instructions for installation, and more detailed instructions on Picoprobe and RP2040 development in general with the C SDK can be found in the [Getting started with Raspberry Pi Pico](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf) and [Raspberry Pi Pico C/C++ SDK](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf) books."

I have indeed found the additional information in the pdf you mentioned. I also agree with the decision to provide short-form instructions. But to me (a new user without much prior knowledge), it looks like the instructions are wrong / incomplete, as they do not work on a the default installation of Raspberry Pi OS, as it doesn't have the pi pico sdk pre-installed.

Therefore I would ask to reconsider to add these 4 lines into the section about hacking, so the instructions will work on a default installation of Raspberry Pi OS:
$ git clone https://github.com/raspberrypi/pico-sdk.git --branch master
$ cd pico-sdk
$ git submodule update --init
$ cd ..

**Comment by lurch** [comment]
If you're _only_ building picoprobe, you could also replace `cmake ..` with `PICO_SDK_FETCH_FROM_GIT=1 cmake ..` which is even shorter. Many ways to skin a cat, etc. :wink:

**Pull request closed without merging**
