### PR TITLE
buildsystem improvements to make it easier to build for debugprobe.

### PR DESCRIPTION
**Pull request by rewolff**
This allows a cmake commandline option to build for debugprobe. 

it seems that such a "stacked" pull request includes the previous changes. So this also includes the README.md changes I did previously. Blame my inexperience with git.

### CODE REVIEW

**Comment by P33M** [comment]
You have 4 commits in your branch because you created it on top of your other pull request. No matter, I'll just retire the old one. However, please address the review comments. I'll squash when merging, despite the PR covering two topics, so just add commits on top.

**Comment by rewolff** [comment]
I can't find any "review comments". Documentation explains how to write them, but not how to view them. And I expect them to show up prominently when present, so no need to document how to find them. To me it looks as if there are none,  so if there are "review comments", I'm afraid you'll have to tell me how to find them.

**Review by P33M — CHANGES_REQUESTED** [review]

**Comment by P33M** [comment]
Fun with github, apparently adding a comment requires you to then hit the "submit review" button or they're not visible

**Comment by rewolff** [comment]
> Fun with github, apparently adding a comment requires you to then hit the "submit review" button or they're not visible
Ah! The docs probably mentioned that. :-) 

Anyway. I'm debating removing  ** the "picoprobe" version of ** in the second paragraph. What do you think? Can I add that as a last commit and then have you decide to include in the squash/merge?

**Comment by rewolff** [comment]
Added one more thing. It now automatically sets the output filename to "debugprobe.elf" etc if you compile for debugprobe. 

I copied over the cmake conditional stuff to my work-project, and then there I figured out how to change the binaryname and copied it over to here. :-) Nice.

**Pull request merged**
