### PR TITLE
Add MS OS Descriptor 2.0 to load WinUSB automatically on Windows.

### PR DESCRIPTION
**Pull request by ciniml**
This PR adds MS OS Descriptor 2.0 to load WinUSB driver automatically on Windows.

MS OS 2.0 Descriptor spec is here.
https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/microsoft-os-2-0-descriptors-specification

I've confirmed that this modification works with Windows 10 Pro 20H2, and OpenOCD can access to the picoprobe correctly.

I think this PR solves #15, because after this modification we don't need to install driver with Zadig anymore.

### CODE REVIEW

**Comment by lurch** [comment]
That page says "Please read the license agreement before continuing." and I'm not familiar enough with legalese to be able to tell if that licence allows Open Source implementations, so pinging @ghollingworth

**Comment by mcuee** [comment]
If you want to support Windows 7 then it is better to use the old MS OS 1.0 descriptors.
https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/microsoft-defined-usb-descriptors

**Comment by aallan** [comment]
> If you want to support Windows 7…

There is no official support for Windows versions before Windows 10.

**Comment by mcuee** [comment]
> > If you want to support Windows 7…
> 
> There is no official support for Windows versions before Windows 10.

I see. In that case, MS OS 2.0 descriptor is better as it better designed.

**Comment by ghollingworth** [comment]
I'm happy with that license

**Comment by ciniml** [comment]
Hi.
Thanks for commenting to the PR.

In this code, are there any problem which blocks to merge this PR?
If so, I will fix that.

**Comment by DavidEGrayson** [comment]
This pull request appears to be using a device interface GUID of A5DCBF10-6530-11D2-901F-00C04FB951ED, which is [GUID_DEVINTERFACE_USB_DEVICE], a special GUID that Microsoft's hub drivers use.

However, the DeviceInterfaceGUID is supposed to be a GUID indicating what type of interface this device has.  Any application using libusb won't care about it, but there is example from Microsoft showing how to enumerate all the USB devices and then select USB devices based on their DeviceInterfaceGUID.  I recommend generating a new one for the picoprobe with `uuidgen` or `guidgen` and using that.

In case you are not convinced, here is documentation from Microsoft talking about how to get WinUSB working with an INF file, and it says to generate a device interface GUID using guidgen.exe:  https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/winusb-installation

[GUID_DEVINTERFACE_USB_DEVICE]: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-usb-device

**Comment by mcuee** [comment]
Good point to use an unique GUID.

A good reference is here at libwdi wiki site: https://github.com/pbatard/libwdi/wiki/WCID-Devices

**Comment by elfmimi** [comment]
Another choice , you can just omit GUID registry definition from the MSOS20-descriptor.
WinUSB and libusb both work just fine.

**Comment by P33M** [comment]
Superseded by #31, which implements the above (and adds the GUID that Keil specifies for DAP interfaces).

**Pull request closed without merging**
