### PR TITLE
Add a CMSIS compatible implementation for picoprobe

### PR DESCRIPTION
**Pull request by P33M**
- FIx a bug where SWDIO was left low at the end of a write
- Add a PIO driven implementation of CMSIS-DAP transfer APIs
- Add descriptors and task callbacks for v1 (HID) and v2 (Bulk) CMSIS-DAP protocols

For now, leave the default protocol selection set to the existing openocd interface.

### CODE REVIEW

**Comment by UweBonnes** [comment]
Compiling against gcc version 11.2.1 20220111 I get

[ 52%] Building C object CMakeFiles/picoprobe.dir/home/bon/devel/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
/home/bon/devel/pico/pico-sdk/src/rp2_common/pico_printf/printf.c: In function _ftoa':
/home/bon/devel/pico/pico-sdk/src/rp2_common/pico_printf/printf.c:354:5: internal compiler error: Illegal instruction
  354 |     if (value < -DBL_MAX)
      |     ^~
0x1521b50 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x15227d6 internal_error(char const*, ...)
        ???:0
0xb7838f crash_signal(int)
        ???:0
0x171b289 __gmpn_mul_basecase
        ???:0

Building with gcc-arm-none-eabi-10.3-2021.10 works.

**Comment by P33M** [comment]
If GCC is crashing then that seems like a bug with GCC, no?

In any case the bug is triggered from code in the SDK. Might be worth raising the issue on the SDK repo instead.

**Comment by UweBonnes** [comment]
Thanks for the pointer. With blackmagic hosted (BMDA), I was able to read from another RP-PICO at about 81 kB/s

**Comment by UweBonnes** [comment]
https://github.com/blackmagic-debug/blackmagic. The first test used the default 4 M. With higher speed, I get ´´´> ./blackmagic -f 16M -S 100k -r /tmp/bla
Black Magic Debug App v1.8.0-211-g018fc517
 for Black Magic Probe, ST-Link v2 and v3, CMSIS-DAP, JLink and libftdi/MPSSE
Using 2e8a:000c E660C0D1C7305737 Raspberry Pi
 Picoprobe
Read/Verify succeeded for 102400 bytes,  124.878 kiB/s´´´

**Comment by UweBonnes** [comment]
B.t.w, https://git.lain.faith/sys64738/DragonProbe.git is another CMSIS-DAP for RP Pico with SDW/JTAG Pio implementation.

**Comment by P33M** [comment]
> I would love to see a blackmagic firmware implementation for the Pico.

As of 1.8.0 it appears to do so - https://github.com/blackmagic-debug/blackmagic/releases/tag/v1.8.0

**Comment by UweBonnes** [comment]
This is with RP Pico as a target, but not as a debugger host running the blackmagic firmware.

**Comment by elfmimi** [comment]
I find it nice for all of us to have a natural implementation of PIO + CMSIS-DAP for RasPi Pico like this.
But I want merging of it considered thoughtfully.
Doesn't it going to spoil the simplicity of picoprobe which is excel at serving a great learning opportunity for someone new to SWD?

**Comment by P33M** [comment]
The functionality is no different. In fact using CMSIS-DAP v2 makes setup on Windows easier, as you don't have to manually assign the interface driver using Zadig.

**Comment by flaviut** [comment]
I've been able to get this working.

1. Build and install [the latest version of OpenOCD](https://github.com/openocd-org/openocd) from git[^1]. If you're from the future, you need OpenOCD v0.12.0.
2. Build this branch, or [download the attached UF2 file](https://github.com/raspberrypi/picoprobe/files/9847387/picoprobe.zip), and flash it onto your Pico.
3. Use the following command to flash the program: `openocd -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c 'adapter speed 10000; program {build/MyProgram} verify reset;'`
4. Open a debugger using `arm-none-eabi-gdb build/MyProgram`. Run `target remote :3333` to attach to the target device core 0. Run `target remote :3334` to attach to core 1.[^2]

[^1]: this is required because we need an OpenOCD [with this patch](https://github.com/openocd-org/openocd/commit/92169e9f5529959aa63f13c47c3975dfe90a686b).
[^2]: my understanding is that the dual-debugger situation will be resolved in 0.13.0, [when a different change will allow for multiple threads in the same debugger](https://review.openocd.org/c/openocd/+/7275/2#message-4851c972eb1d1cf3ed52522cee535806135f34bf).

**Comment by pingufreak** [comment]
I'm testing this, but the speed is still the same as before with the normal picoprobe. I'm getting:

> target halted due to debug-request, current mode: Thread

**Comment by flaviut** [comment]
You're right @pingufreak. I hadn't paid much attention to the speed, but this is still super slow. Here's a fix to take it from 4KiB/s to theoretically 500KiB/s:

<details>

```patch
commit be2ef5ada5d357efe4ac6b99727735881d418bbf (HEAD -> picodebug)
Author: Flaviu Tamas <tamasflaviu@gmail.com>
Date:   Fri Oct 28 17:58:53 2022 -0400
 
    Improve debugger performance
    
    DAP_PACKET_COUNT indicates the number of messages that the probe may
    have in flight at any time. With this set to 2, the computer is forced
    to send just two messages, wait for those messages to be replied to, and
    then submit remaining messages. Looks like in practice, a message is a
    single word flash read or write.
    
    Since USB places a minimum bound of 2ms delay on each message, that
    comes out to an absolute max speed of 3.9KiB/s.
    
    If we instead change this to allow 255 messages simultaniously in
    flight, we get a theoretical max of 500KiB/s since our pipeline is much
    wider.
    
    Unfortunately, I think this is the best we can do with the RP2040 as the
    debugger. USB full-speed supports a max packet size of 64, so while DAP
    allows packets up to 1024 bytes, we can't do that because we'd have to
    use USB high-speed.
 
diff --git a/include/DAP_config.h b/include/DAP_config.h
index e05e27b..e84a704 100755
--- a/include/DAP_config.h
+++ b/include/DAP_config.h
@@ -95,7 +95,7 @@ This information includes:
 /// This configuration settings is used to optimize the communication performance with the
 /// debugger and depends on the USB peripheral. For devices with limited RAM or USB buffer the
 /// setting can be reduced (valid range is 1 .. 255).
-#define DAP_PACKET_COUNT        2U              ///< Specifies number of packets buffered.
+#define DAP_PACKET_COUNT        255U              ///< Specifies number of packets buffered.
 
 /// Indicate that UART Serial Wire Output (SWO) trace is available.
 /// This information is returned by the command \ref DAP_Info as part of <b>Capabilities</b>.
 ```

</details>

```
$ time openocd -d2 -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c 'adapter speed 10000; program {file} verify reset exit;'
...
openocd -d2 -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c   0.11s user 0.48s system 8% cpu 6.628 total
```

[U2F file download](https://github.com/raspberrypi/picoprobe/files/9892221/picoprobe.zip) (I also updated my original comment)

**Comment by P33M** [comment]
While the performance comparisons are useful they are out of scope. This pull request does as the title says it does - change the driver interface to one that's more widely supported.

**Comment by flaviut** [comment]
@P33M Understood--however in this particular case, the performance improvement comes from a 1-line config file change. It might be nice to get it in in the same changeset to avoid a perhaps months-long delay in merging it as another PR.

**Comment by pingufreak** [comment]
@P33M : You are right. Just one note at the end, it works for me now. It's pretty fast and I like it!

**Comment by jandy123** [comment]
Will JTAG transport be supported? 

Thanks and great work, btw.

**Comment by jandy123** [comment]
> You're right @pingufreak. I hadn't paid much attention to the speed, but this is still super slow. Here's a fix to take it from 4KiB/s to theoretically 500KiB/s:
> 
> ```
> $ time openocd -d2 -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c 'adapter speed 10000; program {file} verify reset exit;'
> ...
> openocd -d2 -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c   0.11s user 0.48s system 8% cpu 6.628 total
> ```
> 
> [U2F file download](https://github.com/raspberrypi/picoprobe/files/9892221/picoprobe.zip) (I also updated my original comment)

This does not do anything for me. Speed is the same... flashing over swd a stm32f1xxx target at about 26kB/sec.

**Comment by jandy123** [comment]
> If in a VM, verify you use USB2/3 instead of USB1 ;)

Sorry, but I'm a bit lost.  Is there anything to gain in practice? I mean, the device is USB 1.1...

**Comment by lurch** [comment]
> Will JTAG transport be supported?

See #44

**Comment by BobyClaws** [comment]
with openocd 0.12.0-rc2 and picoprobe-cmsis-v1.0.1 my timers are no longer running with the following prelaunch commands for cortex-debug in vscode
            "preLaunchCommands": [
                "monitor init",
                "monitor reset init",
                "monitor halt",
            ],
this used to work with the customer openocd and older version of picoprobe. am I missing something

**Comment by P33M** [comment]
Please open a new issue in this repo.

**Pull request merged**
